### ISSUE TITLE
Docusaurus-fix

### ISSUE THREAD

**Issue by marikvistad** [VolueSpark/spark-docs#22]
- [x] Startside som første side i menypunkt docs (se hierarki på [Ionic docs ](https://ionicframework.com/docs)if confused :)) 
- [x] Oppdatere logo i footer 
- [x] Rydde opp i navngivning av sider for å unngå duplikater og mye klikking
- [x] Illustrasjoner (use cases) - se skisser
- [ ] Eksterne linker må ha ikon bak (gjelder bla. link til Storybook under use cases, linker under Getting started)
- [x] Aligne innhold i footer

**Comment by joningehe** [comment]
Følgende punkter trenger litt utdypning/diskusjon:

- Release notes: kan sette opp template så langt, men må få diskutert rundt hvordan det skal se ut, struktureres og hva innhold vi skal ha med
- Was this useful: må samle inn data
- FAQ: trenger QA
